# docker-compose.yml

version: "3.8"
services:
  mongo:
    env_file: ".env"
    image: mongo:5.0
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./database/db:/data/db
      - ./database/dev.archive:/Databases/dev.archive
      - ./database/production:/Databases/production
  mongo-express:
    image: mongo-express
    container_name: mexpress
    env_file: ".env"
    links:
      - mongo
    restart: unless-stopped
    ports:
      - "8081:8081"